//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTaleem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblComplaint
    {
        public int ComplaintID { get; set; }
        public string ComplaintTitle { get; set; }
        public string ComplaintDescription { get; set; }
        public int CategoryID { get; set; }
        public long UserID { get; set; }
        public string ComplaintStatus { get; set; }
        public string ComplaintDate { get; set; }
        public bool IsVisible { get; set; }
    }
}
