//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTaleem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmergency
    {
        public int EmergencyID { get; set; }
        public string EmergencyTitle { get; set; }
        public long UserID { get; set; }
        public string EmergencyLocation { get; set; }
        public string EmergencyStatus { get; set; }
        public bool IsVisible { get; set; }
    }
}
