//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTaleem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFeedback
    {
        public int FeedbackID { get; set; }
        public long UserID { get; set; }
        public string FeedbackDate { get; set; }
        public string FeedbackDescription { get; set; }
        public bool IsVisible { get; set; }
        public bool IsSeen { get; set; }
    }
}
