//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTaleem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSession
    {
        public int SessionID { get; set; }
        public string SessionBegin { get; set; }
        public string SessionEnd { get; set; }
        public string SessionLocation { get; set; }
        public long UserID { get; set; }
    }
}
